# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RDML
email: your-email@example.com
description: >
  The Real-time PCR Data Markup Language (RDML) is a structured and universal data
  standard for exchanging quantitative PCR (qPCR) data. The data standard should
  contain sufficient information to understand the experimental setup, re-analyse
  the data and interpret the results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rdml.org"
canonurl: "https://rdml.org"
github_username:  rdml-org

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
encoding: UTF-8
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - favicon/
  - LICENSE
